if(!javaxt)var javaxt={};if(!javaxt.dhtml)javaxt.dhtml={};
if(!javaxt)var javaxt={};if(!javaxt.express)javaxt.express={};javaxt.express.SQLEditor=function(parent,config){this.className="javaxt.express.SQLEditor";var me=this;var tree,sql,grid,gridContainer;var runButton,cancelButton;var jobID;var defaultConfig={queryService:"sql/job/",getTables:"sql/tables/",pageSize:50,style:{container:{width:"100%",height:"100%",background:"#1c1e23",},leftPanel:{background:"#272a31",borderRight:"1px solid #383b41"},table:javaxt.dhtml.style.default.table,toolbarButton:javaxt.dhtml.style.default.toolbarButton}};var border="1px solid #383b41";var init=function(){if(typeof parent==="string"){parent=document.getElementById(parent);}
if(!parent)return;config=clone(config);config=merge(config,defaultConfig);var div=document.createElement('div');setStyle(div,config.style["container"]);var table=createTable();var tbody=table.firstChild;var tr=document.createElement('tr');tbody.appendChild(tr);var td;var td=document.createElement('td');setStyle(td,config.style["leftPanel"]);td.style.height="100%";tr.appendChild(td);createTableView(td);td=document.createElement('td');td.style.height="100%";td.style.width="100%";tr.appendChild(td);createQueryView(td);div.appendChild(table);parent.appendChild(div);me.el=div;var w=me.el.offsetWidth;if(w===0||isNaN(w)){var timer;var checkWidth=function(){var w=me.el.offsetWidth;if(w===0||isNaN(w)){timer=setTimeout(checkWidth,100);}
else{clearTimeout(timer);onRender();}};timer=setTimeout(checkWidth,100);}
else{onRender();}};var onRender=function(){get(config.getTables,{success:function(text){var tables=JSON.parse(text).tables;tree.addNodes(tables);}});};var createTableView=function(parent){var outerDiv=document.createElement("div");outerDiv.style.position="relative";outerDiv.style.height="100%";outerDiv.style.width="210px";outerDiv.style.overflow="auto";parent.appendChild(outerDiv);var div=document.createElement('div');div.style.position="absolute";div.style.width="100%";outerDiv.appendChild(div);tree=new javaxt.dhtml.Tree(div,{style:{padding:"7px 0 7px 0px",backgroundColor:"",li:"tree-node"}});tree.onClick=function(item){sql.value="select * from "+item.name;};};var createQueryView=function(parent){var table=createTable();var tbody=table.firstChild;var tr,td;tr=document.createElement('tr');tbody.appendChild(tr);td=document.createElement('td');tr.appendChild(td);td.className="button-toolbar";addButtons(td);tr=document.createElement('tr');tbody.appendChild(tr);td=document.createElement('td');td.style.borderBottom=border;tr.appendChild(td);sql=document.createElement('textarea');sql.style.width="100%";sql.style.height="240px";sql.style.margin=0;sql.style.padding="5px 10px";sql.style.border="0px none";sql.style.resize="none";sql.style.fontFamily='"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace';sql.style.color="#97989c";sql.style.background="inherit";td.appendChild(sql);tr=document.createElement('tr');tbody.appendChild(tr);td=document.createElement('td');td.style.height="100%";td.style.verticalAlign="top";td.style.fontFamily='"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace';td.style.color="#97989c";tr.appendChild(td);gridContainer=td;parent.appendChild(table);};var addButtons=function(toolbar){runButton=createButton(toolbar,{label:"Run",icon:"runIcon",disabled:false});runButton.onClick=function(){cancel();gridContainer.innerHTML="";grid=null;var url=config.queryService;var payload={query:sql.value,limit:config.pageSize};getResponse(url,JSON.stringify(payload),function(request){var json=JSON.parse(request.responseText);var data=parseResponse(json);render(data.records,data.columns);});};cancelButton=createButton(toolbar,{label:"Cancel",icon:"deleteIcon",disabled:true});cancelButton.onClick=function(){cancel();};};var cancel=function(){if(jobID){javaxt.dhtml.utils.delete(config.queryService+jobID,{success:function(){cancelButton.disable();},failure:function(request){cancelButton.disable();if(request.status!==404){showError(request);}}});}
jobID=null;};var showError=function(msg){cancelButton.disable();if(msg.responseText){msg=(msg.responseText.length>0?msg.responseText:msg.statusText);}
gridContainer.innerHTML=msg;};var getResponse=function(url,payload,callback){post(url,payload,{success:function(text){jobID=JSON.parse(text).job_id;cancelButton.enable();var timer;var checkStatus=function(){if(jobID){var request=get(config.queryService+jobID,{success:function(text){if(text==="pending"||text==="running"){timer=setTimeout(checkStatus,250);}
else{clearTimeout(timer);callback.apply(me,[request]);}},failure:function(response){clearTimeout(timer);showError(response);}});}
else{clearTimeout(timer);}};timer=setTimeout(checkStatus,250);},failure:function(response){showError(response);}});};var parseResponse=function(json){var rows=json.rows;var record=rows[0];var columns=[];for(var key in record){if(record.hasOwnProperty(key)){columns.push(key);}}
var records=[];for(var i=0;i<rows.length;i++){var record=[];var row=rows[i];for(var j=0;j<columns.length;j++){var key=columns[j];var val=row[key];record.push(val);}
records.push(record);}
return{columns:columns,records:records};};var render=function(records,columns){if(grid){var currPage=grid.getCurrPage();grid.load(records,currPage+1);}
else{var arr=[];var colWidth=(100/columns.length)+"%";for(var i=0;i<columns.length;i++){arr.push({header:columns[i],width:colWidth,sortable:false});}
grid=new javaxt.dhtml.DataGrid(gridContainer,{columns:arr,style:config.style.table,url:config.queryService,payload:JSON.stringify({query:sql.value}),limit:config.pageSize,getResponse:getResponse,parseResponse:function(request){return parseResponse(JSON.parse(request.responseText)).records;}});grid.beforeLoad=function(page){};grid.afterLoad=function(){cancelButton.disable();};grid.onSelectionChange=function(){};grid.load(records,1);}};var createButton=function(toolbar,btn){btn.style=JSON.parse(JSON.stringify(config.style.toolbarButton));if(btn.icon){btn.style.icon="toolbar-button-icon "+btn.icon;delete btn.icon;}
if(btn.menu===true){btn.style.arrow="toolbar-button-menu-icon";btn.style.menu="menu-panel";btn.style.select="panel-toolbar-menubutton-selected";}
return new javaxt.dhtml.Button(toolbar,btn);};var get=javaxt.dhtml.utils.get;var post=javaxt.dhtml.utils.post;var del=javaxt.dhtml.utils.delete;var clone=javaxt.dhtml.utils.clone;var merge=javaxt.dhtml.utils.merge;var setStyle=javaxt.dhtml.utils.setStyle;var createTable=javaxt.dhtml.utils.createTable;init();};