
CREATE TABLE SOURCE (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(75) NOT NULL UNIQUE,
    DESCRIPTION text,
    ACTIVE boolean NOT NULL DEFAULT true,
    ACCOUNT_NUMBER text,
    INFO jsonb,
    CONSTRAINT PK_SOURCE PRIMARY KEY (ID)
);


CREATE TABLE ACCOUNT (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(75) NOT NULL UNIQUE,
    DESCRIPTION text,
    ACTIVE boolean NOT NULL DEFAULT true,
    INFO jsonb,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
);


CREATE TABLE CATEGORY (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(75) NOT NULL,
    DESCRIPTION text,
    ACCOUNT_ID bigint,
    INFO jsonb,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID)
);


CREATE TABLE VENDOR (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(75) NOT NULL UNIQUE,
    DESCRIPTION text,
    ACTIVE boolean NOT NULL DEFAULT true,
    INFO jsonb,
    CONSTRAINT PK_VENDOR PRIMARY KEY (ID)
);


CREATE TABLE TRANSACTION (
    ID BIGSERIAL NOT NULL,
    DATE TIMESTAMP with time zone NOT NULL,
    DESCRIPTION text,
    NOTES text,
    AMOUNT numeric NOT NULL,
    SOURCE_ID bigint NOT NULL,
    VENDOR_ID bigint,
    CATEGORY_ID bigint,
    INFO jsonb,
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (ID)
);


CREATE TABLE RULE (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(75) NOT NULL UNIQUE,
    DESCRIPTION text,
    ACTIVE boolean NOT NULL DEFAULT true,
    INFO jsonb,
    CONSTRAINT PK_RULE PRIMARY KEY (ID)
);



ALTER TABLE CATEGORY ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE TRANSACTION ADD FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSACTION ADD FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSACTION ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
    ON DELETE SET NULL ON UPDATE NO ACTION;



CREATE INDEX IDX_CATEGORY_ACCOUNT ON CATEGORY(ACCOUNT_ID);
CREATE INDEX IDX_TRANSACTION_SOURCE ON TRANSACTION(SOURCE_ID);
CREATE INDEX IDX_TRANSACTION_VENDOR ON TRANSACTION(VENDOR_ID);
CREATE INDEX IDX_TRANSACTION_CATEGORY ON TRANSACTION(CATEGORY_ID);
